---
title: "AC KI Pipeline Doku"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Anwendungscampus KI 
- Entwicklung einer Pipeline für Data Matching und Visualisation
- Ab Sprint 1 (Transfer von Python zu R)
- R Paket für ...
  - eigenen ML-Model trainer and builder (bzw. Optimizer), Preprocess, Matching, Visualisation Wrapper, 
  - Integration einfacher Handhabung
  - Ausführliche Doku
  - Zeitliche Begrenzung beachtend
  - Pipeline builder?

# TODO

- functions
  - [ ] **auto_preprosses**: wrapper for commonly used preprocessing and its optimization 
  - [ ] **auto_train**: train an optimized model (type+parameter) for classification and regression problems under fixed time
  - [ ] **auto_transfer**: transfer trained model to another dataset, uses different sample methods depending on the relationship between datasets (as input, e.g. Markov transition matrix, Correlation Kernel)
  - [ ] **plot**: standard Plots
- [ ] write tests and docu
  

# Done 
## 26.01.2022
- [x] changed structure of preprocessing using the pipe: (Invention?)

## 24.01.2022
- [x] Setup Package and Interface
- [x] **read_all_files**: import all CSV and SAS files from folder

# References

## About R 
### Building Packages
  - 5min Introduction: https://www.youtube.com/watch?v=MoszELQFrvQ
  - Free EBook (click "-/-/-" for toc): https://r-pkgs.org/
  
### Programming
  - Pipe Operator Tutorial: https://www.datacamp.com/community/tutorials/pipe-r-tutorial 

## ML 

# Examples

```{r}
library(awKI)
hello()
```


